### ISSUE TITLE
feature request - module for catalog requests/cart

### ISSUE THREAD

**Issue by gforster** [ServiceNowITOM/servicenow-ansible#10]
Requesting a module to automate submitting a form to a catalog request and kicking off the REQ/RITM/SCTASK

have a number of things that have been made self-service, but humans filling out forms for repeatable requests is prone to error and could be automated.

**Comment by willtome** [comment]
@gforster it does not look like pysnow library has any catalog capabilities so we'd need to consider another way of implementing this

**Comment by willtome** [comment]
Please raise this feature request here https://github.com/ansible-collections/servicenow.itsm

Thank you!
