### ISSUE TITLE
servicenow.servicenow.now inventory plugin has an unrecognized documentation field.

### ISSUE THREAD

**Issue by abadger** [ServiceNowITOM/servicenow-ansible#14]
The following line (`secret: true`) in the now inventory plugin docs is unrecognized: https://github.com/ServiceNowITOM/servicenow-ansible/blob/devel/plugins/inventory/now.py#L39

It should be removed as once we start validating plugin documentation, it will cause the inventory plugin to fail to parse.

**Comment by willtome** [comment]
Resolved by PR #15
