### ISSUE TITLE
ERROR! 'collections' is not a valid attribute for a Play

### ISSUE THREAD

**Issue by indirakas** [ServiceNowITOM/servicenow-ansible#28]
I am trying to use the snow_record module from servicenow.servicenow collection, but I am getting an error:
`ERROR! 'collections' is not a valid attribute for a Play`

Ansible 2.9.10 is being used.

Here is my playbook:

- name: Open Servicenow
  hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - servicenow.servicenow

  tasks:

    - name: Create an incident
      snow_record:
        username: "{{ rest_user }}"
        password: "{{ rest_password }}"
        instance: esnetdev.servicenowservices.com
        state: present
        data:
          short_description: "Ansible job on {{tower}} has failed"
          assignment_group: "Networking"
          description: "Paste description here"
          severity: 3
          priority: 2

**Comment by bmwt** [comment]
Are we sure this is ansible 2.9?  that error usually appears in older versions without collection support.
I tried testing this a bit, and the road block i ran into was actually dealing with the hostname.  On the ansible 2.9 version of the snow module, it only supports the "instance" option, which is *not* an fqdn- rather, it points to a hostname in the service-now.com domain (which we dont currently have.  It's expanding to esnetdev.servicenowservices.com.service-now.com).  2.10 introduced a "host" option which lets you specify a FQDN (but that field appears not to work in 2.9)

**Comment by bmwt** [comment]
note that the NEG venv on tower is currently at 2.7.10 (which lacks collections support)

**Comment by willtome** [comment]
Unable to reproduce. Error may be a result of incorrect formatting.
