### ISSUE TITLE
FEATURE REQUEST: add ability to set sysparm_display_value in snow.yaml inventory file

### ISSUE THREAD

**Issue by craigers521** [ServiceNowITOM/servicenow-ansible#38]
for the inventory plugin the syspam_display_value seems to be hardcoded into options variable with value set to "True" in now.py file. 

```
options = "?sysparm_exclude_reference_link=true&sysparm_display_value=true"
```

It would be nice to have this as a configurable option so my CMDB has "friendly" names but ansible can consume the actual values for the vars it needs.  

Apologies if this is a duplicate of issue #35 but i looked at the PR at it seems like this functionality was added to snow record module but not inventory module/plugin

**Comment by willtome** [comment]
Please raise this feature request against the new plugin here https://github.com/ansible-collections/servicenow.itsm

Thank you
