### ISSUE TITLE
Getting shared connection closed while using snow_record_find module

### ISSUE THREAD

**Issue by charishma1** [ServiceNowITOM/servicenow-ansible#40]
While using snow_record_find to search for an existing ticket in servicenow ,am getting the error shared connection closed and task is not executed.
But the same search is working when  i use curl to interact with snow api.
This looks like a randome issue,few times it works and some times not.

**Comment by n3pjk** [comment]
Can you provide more information? Details, like the exact error message? Without any further details, I would direct you to [this article](https://www.tecmint.com/fix-shared-connection-to-x-x-xx-closed-ansible-error/). It may be a problem with the way your python environment is set up.
