### ISSUE TITLE
In Ansible Tower - servicenow.servicenow collection plugin imports inventory with IP instead of names. How can you import inventory as name?

### ISSUE THREAD

**Issue by rvermausa** [ServiceNowITOM/servicenow-ansible#42]
In Ansible Tower - servicenow.servicenow collection plugin imports inventory with IP instead of names. How can you import inventory as name?

I have used the following info to setup servicenow.servicenow collection plugin.

https://www.ansible.com/blog/using-an-inventory-plugin-from-a-collection-in-ansible-tower

Please help.

**Comment by willtome** [comment]
Set the `selection_order` option to the name of the field that you want to use. 

From: https://github.com/ServiceNowITOM/servicenow-ansible/blob/devel/docs/inventory.md
The default order is `ip_address,fqdn,host_name,name`

**Comment by rvermausa** [comment]
Thanks.  I was able to fix this issue via slection_order quite a while ago.  Thanks for the verification.
