### ISSUE TITLE
snow_record module gives SSL error

### ISSUE THREAD

**Issue by Sethueha** [ServiceNowITOM/servicenow-ansible#48]
The full traceback is:
WARNING: The below traceback may not be related to the actual failure.
File "/tmp/ansible_snow_record_payload_veyqtK/ansible_snow_record_payload.zip/ansible/modules/notification/snow_record.py", line 303, in run_module
File "/usr/lib/python2.7/site-packages/pysnow/legacy_request.py", line 142, in get_one
fields, limit=None, order_by=list(), offset=None
File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 555, in get
return self.request('GET', url, **kwargs)
File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 542, in request
resp = self.send(prep, **send_kwargs)
File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 655, in send
r = adapter.send(request, **kwargs)
File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 514, in send
raise SSLError(e, request=request)
fatal: [host]: FAILED! => {
"ansible_facts": {
"discovered_interpreter_python": "/usr/bin/python"
},
"attachment": "/var/log/ansible/server_12-03-2021_RITM0062190.log",
"changed": false,
"instance": "hpe",
"invocation": {
"module_args": {
"attachment": "/var/log/ansible/server_12-03-2021_RITM0062190.log",
"client_id": null,
"client_secret": null,
"data": null,
"instance": "hpe",
"lookup_field": "number",
"number": "RITM0062190",
"password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
"state": "present",
"table": "sc_req_item",
"username": ""
}
},
"lookup_field": "number",
"msg": "Failed to update record: HTTPSConnectionPool(host='', port=443): Max retries exceeded with url: /api/now/table/sc_req_item?sysparm_query=number%3DRITM0062190 (Caused by SSLError(SSLError(1, u'[SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:618)'),))",
"number": "RITM0062190",
"table": "sc_req_item"
}

**Comment by n3pjk** [comment]
This exception looks like it is being thrown by the requests module, as it does not recognize the SSL protocol in use. It is trying to access https://hpe.service-now.com. Is that correct? You might try specifying the host instead of the instance as 'host: hpe.service-now.com' and see if that yields different results. If you are going through a proxy, check that your proxy environment variables are correctly set.
