### ISSUE TITLE
dynamic ssh_port servicenow dynamic inventory 

### ISSUE THREAD

**Issue by kumaresan078** [ServiceNowITOM/servicenow-ansible#49]
Hi All,

I am pulling dynamic inventory with servicenow and few hosts we are using different ssh port.Could someone help how to change ssh port for few hosts from 22 to 8888 dynamically while pulling inventory based on host name?

Any help would be appreciated.

Regards 
Kumar

**Comment by willtome** [comment]
Is the SSH port in the CMDB?
