### ISSUE TITLE
Query multiple incident state and configuration item

### ISSUE THREAD

**Issue by kumaresan078** [ServiceNowITOM/servicenow-ansible#52]
Hi All,

I am trying to pull incident which are in opened state(either new or work in progress) but the condition not working with or operator also in addition the configuration item which are part of the incident information not getting it.

Not sure below fields or the format is correct.

state: 1 or 2
- configuration_item

Could someone help here?

---
- name: Create ticket with notes
  hosts: localhost
  gather_facts: no
  connection: local
  tasks:
  - name: Fetch Open incidents  
    servicenow.servicenow.snow_record_find:
      username: "{{ USERNAME }}"
      password: "{{ PASSWORD }}"
      instance: "{{ INSTANCE }}"
      table: incident
      query:
        AND:
          equals:
            active: "True"
            assignment_group: "{{ group }}"
            state: "1" or "2"
          return_fields:
           - number
           - opened_at
           - short_description
           - configuration_item

      

    register: fetch_incident

  - debug: 
      var: fetch_incident

**Comment by n3pjk** [comment]
You could do two separate invocations. In the first one, use "state: 1", and "register: incident_state1". In the second, use "state: 2", and "register: incident_state2". Then use set_fact to combine the records from each response into a single set. Something like:
`set_fact:`
`    incidents: "{{ incident_state1.record | default([]) }} + {{ incident_state2.record | default([]) }}"`

**Comment by willtome** [comment]
For further assistance, please raise an issue here https://github.com/ansible-collections/servicenow.itsm
