### ISSUE TITLE
Inventory Plugin: Create Variables from Reference Attribute Fields

### ISSUE THREAD

**Issue by dmaple-gci** [ServiceNowITOM/servicenow-ansible#55]
I needed the inventory module to pull fields from reference links beyond just the display value. For example, 'location' is a reference attribute from a separate table. I can include 'location' in the fields list and get the display value for a host. To get other fields from that reference, like region, I can request 'location.u_loc_region'. With the pysnow module, I can get this:
```
{
    "name": "<some host>",
    "location": "MOC",
    "location.u_loc_region": "East",
    ...
}
```
The problem is, that results in a host variable named 'sn_location.u_loc_region' which is not usable from ansible.
```
          sn_location: MOC
          sn_location.u_loc_region: East
```
There may be a more elegant way to do this, but I applied the following change to get around this:
```
diff --git a/plugins/inventory/now.py b/plugins/inventory/now.py
index eaa64be..f778dd8 100644
--- a/plugins/inventory/now.py
+++ b/plugins/inventory/now.py
@@ -286,7 +286,9 @@ class InventoryModule(BaseInventoryPlugin, Constructable, Cacheable):

             # set variables for host
             for k in record.keys():
-                self.inventory.set_variable(host_name, 'sn_%s' % k, record[k])
+                # Replace any dots in the variable name
+                v = k.replace(".","_")
+                self.inventory.set_variable(host_name, 'sn_%s' % v, record[k])

             # add relationship based groups
             if enhanced and enhanced_groups:
```
Now, I get a usable variable name:
```
          sn_location: MOC
          sn_location_u_loc_region: East
```

**Comment by epicanthal** [comment]
@dmaple-gci  I have submitted PR #45 for exactly the same.  I am awaiting further instructions as to how this functionality can be merged.  I'm glad there are others that need this :)

**Comment by amittell** [comment]
PR #45 merged
