### ISSUE TITLE
Check for missing commits vs devel

### ISSUE THREAD

**Issue by gundalow** [ServiceNowITOM/servicenow-ansible#7]
##### SUMMARY
The "Big Migration" has now taken place.

As this collection already exists, we need to carefully check to see if any further commits went into devel since this repo was created.

Please check the contents of https://github.com/ansible-collection-migration/servicenow.servicenow against this repo

In particular:
* Please do a per-file level diff against every file in the ansible-collection-migration repo and this one
* Pay care to files added and removed.
* During the last two weeks there have been lots of fixes, especially around and tests, dependencies, and new collection features e.g. meta/action_groups.yml

##### ISSUE TYPE
- Bug Report

**Comment by willtome** [comment]
@gundalow I have compared and update files from the `plugins/` directory. I have a few questions on some other files. 

- Where did the `.gitignore` come from? Do you recommend adopting this?
- Are `tests` and `.github/workflows` a skeleton test framework? How should this used going forward?
- I assume `galaxy.yml` just needs to be present. Not match the migration collection.

**Comment by gundalow** [comment]
## Tests

Rather than using `.github/workflows` from ansible-collection I'd suggest copying the `sanity` test from https://github.com/ansible-collections/grafana/blob/master/.github/workflows/ansible-test.yml#L1-L24
and update https://github.com/ansible-collections/grafana/blob/master/.github/workflows/ansible-test.yml#L1-L24 to be `path: ansible_collections/servicenow/servicenow`

You will need to copy https://github.com/ansible-collection-migration/servicenow.servicenow/tree/master/tests/sanity into this repos 

Do the above in a single PR


## .gitignore

Yup

## galaxy.yml
As long as you are happy with the differences, that's OK

**Comment by willtome** [comment]
Closed by PR #8
