### ISSUE TITLE
Certificate Validation Option

### ISSUE THREAD

**Issue by jpell958** [ServiceNowITOM/servicenow-ansible#73]
We use self signing certificates on our proxy server.  So when we use the SNOW_RECORD module we receive the following message: [SSL: CERTIFICATE_VERIFY_FAILED].  Is there a way to tell the modules in servicenow.servicenow to ignore validating certificates like the URI module?
If currently not, can this be implemented and how quickly?

**Comment by willtome** [comment]
Thank you for raising this issue. This collection is no longer actively maintained. Please reopen the issue with https://github.com/ansible-collections/servicenow.itsm or open a case with Red Hat for a quicker response.

**Comment by jpell958** [comment]
> Thank you for raising this issue. This collection is no longer actively maintained. Please reopen the issue with https://github.com/ansible-collections/servicenow.itsm or open a case with Red Hat for a quicker response.

@willtome - So looking at the new ServiceNow collection it only supports specific built-in tables.  Is this correct?
